-- A reason marker on the devices row, so a give-back pass can prove which cap
-- took a key down (drive#661). `devices.capped_from` records the POWERS a swap
-- took, never the reason: three paths take write powers from a key, and only
-- one of them -- the spending cap freeze (core/cap.js `enforceCap`) -- is a cap
-- the owner set on purpose. A give-back pass that widens a key because its
-- bytes dropped under 1 TB must not widen a key the spending cap froze on
-- purpose (that pass is drive#656).
--
-- The marker is its own nullable TEXT column, not a second entry on
-- `capped_from`: `grantedCapabilities()` in core/cap.js filters that JSON list
-- against the key kind's own scope, so anything that is not a capability name
-- is silently dropped. A reason stored there would vanish on the first read.
--
-- Expansion only, and one phase (fleet D1 expand/contract rule): the column is
-- nullable, carries no DEFAULT, and no backfill runs, so a row written before
-- this file reads as "no reason recorded" exactly as it reads today. Nothing is
-- dropped, renamed or rewritten, so the previous version of the Worker runs
-- unchanged against this schema -- its readers never name the new column and
-- its writers never set it -- which is what keeps the fleet's auto-revert
-- possible. D1 has no down-migrations, so this file is one-way.
--
-- NULL is the only value this phase writes for a raise: the freeze's reason is
-- 'spend-cap' (the spending cap, core/cap.js), and the sweep's
-- 'pre-charge-limit' belongs with drive#655. The prepaid $0-balance pause
-- freezes no key at all -- `core/prepaid.js` `writesPaused()` refuses the write
-- itself on every write -- so it marks nothing, and a row with no reason is a
-- key nothing has capped by reason.
--
-- Numbered 0032, the next free prefix, rather than the 0022 this issue first
-- proposed: `wrangler d1 migrations apply` walks the directory in a
-- full-filename sort (test/d1-sqlite.mjs `orderMigrationFiles`), so a file that
-- sorts BEFORE one already applied makes the deploy refuse, which takes the
-- whole production deploy down. 0026_signin_address_sends.sql owns 0026,
-- 0027_device_queue_reports.sql owns 0027, 0029_welcome_sent_at.sql and
-- 0030_branch_jobs.sql and 0031_signin_return.sql are on disk, and 0028 is a gap a new file must not
-- fill (it would sort before already-applied 0029/0030). drive#619's gate
-- (test/migrations.test.mjs) fails a new file that shares a prefix with
-- another, so the marker takes 0032 and nothing else can race it.
--
-- The new statement depends on nothing before it wrote: it adds one column to
-- `devices`, and every earlier file touches another table or another column.

ALTER TABLE devices ADD COLUMN capped_reason TEXT;
