// Sign-in on Better Auth, over the customer database (drive issue #181, split
// from #161 after that issue timed out with nothing pushed).
//
// What this replaces. src/accounts.js was a hand-written code store: an
// in-memory Map of accounts, one-time codes and sessions, hashed with the api
// Worker's own helpers. Every session it minted lived in the isolate that made
// it, so a request the next isolate served read as signed out — the reason
// drive#2 never shipped a real account store. Better Auth is the library that
// already does this (sessions in the database, links that are single-use and
// expiring, sign-out that revokes), and drive's build spec calls for it by
// name, so the swap is a dependency and not a second implementation.
//
// Where the data lives. One binding, DRIVE_DB — the customer database from
// drive#170 — so an account, its session and its one-time link all sit beside
// the customer's files rather than in the waitlist's database. The four tables
// are migrations/drive/0005_better_auth.sql, generated by Better Auth's own
// migration planner and pinned against it by test/auth.test.mjs.
//
// The closed door is unchanged. `authFor` returns null without the database,
// the signing secret or the public URL, and the route that mints a link
// answers 503 with the message table's words (src/messages.js) rather than
// reporting an email that could not leave. There is no default secret and no
// default URL in this file: Better Auth signs its cookies with `secret` and
// builds every link it mails from `baseURL`, so a deployment with neither set
// is a deployment that is not signed in — not one with a weak session or a
// link that points at the wrong host.
import { betterAuth } from "better-auth";
import { magicLink } from "better-auth/plugins";
import { sendEmail } from "./email-send.js";

/** @typedef {import("./email-send.js").EmailBinding} EmailBinding */

/**
 * The namespace Better Auth puts in front of its cookies. `drive`, so the
 * session cookie is `__Secure-drive.session_token` and not a library's own
 * name: two apps on one domain must not be able to read each other's session.
 */
export const AUTH_COOKIE_PREFIX = "drive";

/**
 * One Better Auth instance, with the magic-link plugin's endpoints on it: the
 * type every route and test in this repo names when it passes the store
 * around, so "no store" is `null` of one type rather than a duck-typed object
 * each call site invents. It is inferred from this factory rather than
 * declared, because the plugin chain is what puts `signInMagicLink` and
 * `magicLinkVerify` on the instance's api and a hand-written type would
 * quietly drop them.
 * @typedef {ReturnType<typeof createAuth>} Auth
 */

/**
 * How long a sign-in link is good for. Ten minutes is the same window the
 * device code has (DEVICE_CODE_TTL_SECONDS in workers/api/src/keystore.js):
 * long enough to find the email, short enough that a link left in a mailbox is
 * dead.
 */
export const SIGNIN_LINK_TTL_SECONDS = 600;

/**
 * How long a session lives, and how often it is refreshed. Thirty days is the
 * browser-session length a person expects from a web app, refreshed when it is
 * used, so signing in every week would be a support ticket rather than a
 * security win.
 */
export const SESSION_TTL_SECONDS = 30 * 24 * 60 * 60;

/**
 * The page a signed-in person lands on after following their link.
 * public/files.html is the drive itself, which is what signing in is for.
 */
export const AFTER_SIGNIN_PATH = "/files";

/**
 * Builds a Better Auth instance over one D1 database.
 *
 * The plugin is the whole sign-in flow: `sendMagicLink` is the one place a
 * link leaves the app, and it is handed to the deployment's own mailer rather
 * than to a second SMTP client. The callback receives the address and the raw
 * token and builds the link itself, so Better Auth never has to know the
 * drive's page layout.
 *
 * @param {{database: unknown, secret: string, baseURL: string, sendLink: (link: {to: string, url: string}) => Promise<unknown>}} options
 */
export function createAuth(options) {
  return betterAuth({
    appName: "drive",
    database: options.database,
    secret: options.secret,
    // The one address this deployment is served on. It is configuration, not
    // something read off the request, because a link mailed to a caller is
    // permanent: a Host header a stranger chose must not be able to decide
    // where the sign-in link in their own inbox points.
    baseURL: options.baseURL,
    // No password and no social providers: the spec's screen asks for one
    // thing (an email link) and the OAuth client ids are Nish's credentials,
    // never values in this repo.
    emailAndPassword: { enabled: false },
    socialProviders: {},
    session: {
      expiresIn: SESSION_TTL_SECONDS,
      // Refresh a session that is still being used, so an active person is not
      // signed out mid-week, and so an abandoned one still expires.
      updateAge: 24 * 60 * 60,
    },
    advanced: {
      cookiePrefix: AUTH_COOKIE_PREFIX,
      // The site is served over HTTPS only (Cloudflare terminates TLS), so the
      // session cookie is `__Secure-` prefixed and never travels in clear.
      useSecureCookies: true,
    },
    plugins: [
      magicLink({
        expiresIn: SIGNIN_LINK_TTL_SECONDS,
        // A first-time address gets an account when it follows its link, and a
        // returning one is found. Both are sign-in, which is why sign-up is
        // left on: the spec's screen has no separate registration step.
        disableSignUp: false,
        sendMagicLink: async ({ email, token }) => {
          await options.sendLink({ to: email, url: signinLink(token, options.baseURL) });
        },
      }),
    ],
  });
}

/**
 * The link the email carries, built by the drive rather than by the library:
 * one path on this Worker, one token in the query, and no library route
 * exposed to a browser. It hangs off the deployment's configured base URL, so
 * it is absolute and it is the address the person actually uses.
 * @param {string} token
 * @param {string} baseURL the deployment's public address
 * @returns {string}
 */
export function signinLink(token, baseURL) {
  return `${baseURL.replace(/\/$/, "")}${SIGNIN_LINK_PATH}?token=${encodeURIComponent(token)}`;
}

/**
 * One auth instance per (D1 binding, base URL), because building one compiles
 * a Kysely dialect and a plugin chain and an isolate serves many requests. The
 * cache is a WeakMap keyed on the binding itself, so a test that builds a
 * fresh in-memory database gets a fresh auth and no two databases ever share
 * one.
 *
 * The box is kept stable so `authFor` can update the mailer each time it is
 * called with a new env object sharing the same binding — the test pattern
 * where env is rebuilt per request while the database stays alive.
 * @type {WeakMap<object, {secret: string, baseURL: string, env: {env: object}, auth: Auth}>}
 */
const AUTH_CACHE = new WeakMap();

/**
 * The auth instance for this request's environment, or null when the
 * deployment cannot have a session at all: no customer database, no signing
 * secret or no public address. Null is the honest answer and every caller
 * treats it as signed out rather than trusting a cookie the browser chose.
 *
 * @param {{DRIVE_DB?: unknown, BETTER_AUTH_SECRET?: string, BETTER_AUTH_URL?: string, EMAIL?: unknown, MAIL_FROM?: string, SIGNIN_MAIL?: (link: {to: string, url: string}) => Promise<unknown>}} env
 * @returns {Auth|null}
 */
export function authFor(env) {
  const database = env.DRIVE_DB;
  const secret = env.BETTER_AUTH_SECRET;
  const baseURL = env.BETTER_AUTH_URL;
  if (
    database === undefined ||
    database === null ||
    typeof database !== "object" ||
    typeof secret !== "string" ||
    secret === "" ||
    typeof baseURL !== "string" ||
    baseURL === ""
  ) {
    return null;
  }
  const cached = AUTH_CACHE.get(database);
  if (cached !== undefined && cached.secret === secret && cached.baseURL === baseURL) {
    cached.env.env = env;
    return cached.auth;
  }
  const box = { env };
  const auth = createAuth({
    database,
    secret,
    baseURL,
    sendLink: (link) => sendSigninLink(box.env, link),
  });
  AUTH_CACHE.set(database, { secret, baseURL, env: box, auth });
  return auth;
}

/**
 * Mails one sign-in link. A deployment with no EMAIL binding, or a test that
 * wants to read what left, supplies its own sender: `SIGNIN_MAIL` is the seam
 * a test reads the link out of, and the token is never in a reply.
 *
 * With neither, this throws rather than returning quietly: a link that cannot
 * be sent must fail the sign-in, and the route turns that failure into the
 * message table's sign-in error instead of telling a person to check an inbox
 * that will stay empty.
 * @param {{EMAIL?: unknown, MAIL_FROM?: string, SIGNIN_MAIL?: (link: {to: string, url: string}) => Promise<unknown>}} env
 * @param {{to: string, url: string}} link
 */
async function sendSigninLink(env, link) {
  if (typeof env.SIGNIN_MAIL === "function") {
    await env.SIGNIN_MAIL(link);
    return;
  }
  const binding = env.EMAIL;
  if (!binding) {
    throw new Error("sign-in needs an EMAIL binding to mail a link");
  }
  await sendEmail(/** @type {EmailBinding} */ (binding), {
    to: link.to,
    kind: "signin-link",
    from: env.MAIL_FROM ?? "",
    rendered: signinLinkEmail(link.url),
  });
}

/**
 * The one email a sign-in link arrives in. Rendered here for the same reason
 * the code email was: it carries a secret, and src/emails.js's table holds the
 * five templates the spec names for customers. A table that also held links
 * would be a place to leak one from.
 * @param {string} url the absolute link, already built by signinLink
 * @returns {{subject: string, text: string, html: string, saved: string|null}}
 */
export function signinLinkEmail(url) {
  const minutes = Math.round(SIGNIN_LINK_TTL_SECONDS / 60);
  return {
    subject: "Your drive sign-in link",
    text: `Sign in to your drive: ${url}\n\nThe link is good for ${minutes} minutes and works once. If you did not ask to sign in, ignore this email.`,
    html: `<p><a href="${url}">Sign in to your drive</a></p><p>The link is good for ${minutes} minutes and works once. If you did not ask to sign in, ignore this email.</p>`,
    saved: null,
  };
}

/** The path the emailed link points at; the route in src/index.js serves it. */
export const SIGNIN_LINK_PATH = "/api/signin/verify";

/**
 * The signed-in account a request carries, or null.
 *
 * This is the whole account gate. The cookie is Better Auth's own signed
 * session token and the lookup is Better Auth's own session query against the
 * customer database, so a made-up value, a forgotten one, an expired one and a
 * revoked one all answer null. Deny by default is the shape: no auth instance,
 * no session or no session's user is `null`, and `null` is what every account
 * route answers 401 to.
 * @param {Request} request
 * @param {{api: {getSession: (options: {headers: Headers}) => Promise<{user: {id: string, name: string, email: string}} | null>}}|null|undefined} auth
 * @returns {Promise<{id: string, name: string, email: string}|null>}
 */
export async function sessionAccount(request, auth) {
  if (!auth) {
    // No auth instance means no database and no signing secret: a cookie the
    // browser chose proves nothing, so it stays signed out.
    return null;
  }
  const found = await auth.api.getSession({ headers: request.headers });
  if (!found?.user || typeof found.user.id !== "string") {
    return null;
  }
  return {
    id: found.user.id,
    name: found.user.name,
    email: found.user.email,
  };
}
